version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://mongoAtlas03:dfal3QmS7Xl3YdW1@cluster0.hubp7gk.mongodb.net/phuongdb?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=R2kSUWXmK9rU28EhYxirY0DZ40RTr5ju0ppH7bkCSwXmALwoHh
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


volumes:
  mongo-data:
